# Generated by Django 3.0.6 on 2020-06-06 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('IdUser', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('userType', models.CharField(max_length=30)),
                ('imgUrl', models.CharField(max_length=100)),
                ('mail', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('race', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=30)),
                ('urlImg', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopcion_backend.User')),
            ],
        ),
    ]
