# Generated by Django 3.0.6 on 2020-06-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='id',
            new_name='idPet',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='IdUser',
            new_name='idUser',
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
