# Generated by Django 3.0.6 on 2020-06-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion_backend', '0003_auto_20200606_0718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='race',
            new_name='type',
        ),
    ]
