# Generated by Django 3.0.6 on 2020-06-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion_backend', '0004_auto_20200607_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idPet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
