# Generated by Django 3.0.7 on 2020-06-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion_backend', '0005_auto_20200607_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
